### ISSUE TITLE
the speedcurve cli crashes on "npmlog" not found

### ISSUE THREAD

**Issue by daton89** [SpeedCurve-Metrics/speedcurve-cli#25]
**What kind of issue is this?**

- [ ] Feature request / PR proposal
- [X] Bug report
- [ ] Question

**Is this issue for the CLI, the Node.js API, or both?**

speedcurve-cli

**What is the current behaviour?**

the speedcurve cli crashes on "npmlog" not found

```sh
npm i -g speedcurve

speedcurve -h

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'npmlog'
Require stack:
- /Users/daton/.nvm/versions/node/v16.15.1/lib/node_modules/speedcurve/dist/log.js
- /Users/daton/.nvm/versions/node/v16.15.1/lib/node_modules/speedcurve/dist/api.js
- /Users/daton/.nvm/versions/node/v16.15.1/lib/node_modules/speedcurve/dist/cli/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/daton/.nvm/versions/node/v16.15.1/lib/node_modules/speedcurve/dist/log.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/daton/.nvm/versions/node/v16.15.1/lib/node_modules/speedcurve/dist/api.js:44:31)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/daton/.nvm/versions/node/v16.15.1/lib/node_modules/speedcurve/dist/cli/index.js:9:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/daton/.nvm/versions/node/v16.15.1/lib/node_modules/speedcurve/dist/log.js',
    '/Users/daton/.nvm/versions/node/v16.15.1/lib/node_modules/speedcurve/dist/api.js',
    '/Users/daton/.nvm/versions/node/v16.15.1/lib/node_modules/speedcurve/dist/cli/index.js'
  ]
}
```

**What is the expected behaviour?**

Command should run without crashing, npmlog seem to be a devDependecy so maybe it should not be included in the dist code or if needed moved to dependencies. 

**Which version is affected by this issue? Did this work in previous versions?**

Latest version 2.0.9
Node 16.15.1

**Comment by josephwynn-sc** [comment]
Apologies for the very slow response on this - I only just saw it! This was a regression in 2.0.9. I have just published version 2.0.10 which works correctly, and I will review our automated testing to try and prevent this from happening again.
